// GENERATED by scripts/convert-claim-forms.mjs — do not hand-edit.
import type { ClaimFormSchema } from "./types";
import aigCorporateTravelClaim from "./aig-corporate-travel-claim.json";
import bryteMotorClaim from "./bryte-motor-claim.json";
import bryteNonMotorClaim from "./bryte-non-motor-claim.json";
import charterRiskMotorGlassClaim from "./charter-risk-motor-glass-claim.json";
import charterRiskMotorVehicleClaim from "./charter-risk-motor-vehicle-claim.json";
import charterRiskPropertyLossDamageClaim from "./charter-risk-property-loss-damage-claim.json";
import glassClaim from "./glass-claim.json";
import guardriskPropertyClaim from "./guardrisk-property-claim.json";
import horizonClaim from "./horizon-claim.json";
import oldMutualMotorAccidentClaim from "./old-mutual-motor-accident-claim.json";
import oldMutualMotorTheftClaim from "./old-mutual-motor-theft-claim.json";
import oldMutualPropertyLossDamageClaim from "./old-mutual-property-loss-damage-claim.json";
import oldMutualPublicLiabilityAccidentReport from "./old-mutual-public-liability-accident-report.json";
import santamDroneClaimsNotification from "./santam-drone-claims-notification.json";
import santamMotorAccidentClaim from "./santam-motor-accident-claim.json";
import sawsCapitalAllianceFuneralClaim from "./saws-capital-alliance-funeral-claim.json";
import sintelumPropertyClaim from "./sintelum-property-claim.json";

export interface ClaimFormRegistryEntry {
  slug: string;
  insurer: string;
  title: string;
  afTitle?: string;
  description?: string;
}

export const CLAIM_FORM_REGISTRY: ClaimFormRegistryEntry[] = [
  {
    "slug": "aig-corporate-travel-claim",
    "insurer": "AIG",
    "title": "Corporate Travel Claim Form",
    "description": "Travel Claim Form"
  },
  {
    "slug": "bryte-motor-claim",
    "insurer": "Bryte",
    "title": "Motor Claim Form",
    "description": "Motor Accident / Motor Theft / Motor Personal Accident · September 2022"
  },
  {
    "slug": "bryte-non-motor-claim",
    "insurer": "Bryte",
    "title": "Non-Motor Claim Form",
    "description": "Non-motor Claims Under R20,000 · March 2021"
  },
  {
    "slug": "charter-risk-motor-glass-claim",
    "insurer": "Charter Risk",
    "title": "Glass Claim Form"
  },
  {
    "slug": "charter-risk-motor-vehicle-claim",
    "insurer": "Charter Risk",
    "title": "Motor Vehicle Claim Form",
    "description": "(Delete Sections not Applicable)"
  },
  {
    "slug": "charter-risk-property-loss-damage-claim",
    "insurer": "Charter Risk",
    "title": "Property Loss / Damage Claim Form"
  },
  {
    "slug": "glass-claim",
    "insurer": "Old Mutual",
    "title": "Glass Claim Form",
    "afTitle": "Glas-Eisvorm",
    "description": "MUFED 1148 7/00"
  },
  {
    "slug": "guardrisk-property-claim",
    "insurer": "Guardrisk",
    "title": "Property Damage Claim Form"
  },
  {
    "slug": "horizon-claim",
    "insurer": "Horizon Underwriting Managers",
    "title": "Transit Claim Form"
  },
  {
    "slug": "old-mutual-motor-accident-claim",
    "insurer": "Old Mutual",
    "title": "Motor Accident Claim Form",
    "afTitle": "Motorongeluk-Eisvorm"
  },
  {
    "slug": "old-mutual-motor-theft-claim",
    "insurer": "Old Mutual",
    "title": "Motor Theft Claim Form",
    "afTitle": "Motordiefstal Eisvorm",
    "description": "MUFED 1630 08/11"
  },
  {
    "slug": "old-mutual-property-loss-damage-claim",
    "insurer": "Old Mutual",
    "title": "Property Loss / Damage Claim Form",
    "afTitle": "Eiendomsverlies / -Skade Eisvorm",
    "description": "MUFED 1599 11/04"
  },
  {
    "slug": "old-mutual-public-liability-accident-report",
    "insurer": "Old Mutual",
    "title": "Public Liability Accident Report Form",
    "afTitle": "Openbare Aanspreeklikheid Ongeluk Verslagvorm",
    "description": "MUFED 1106 1/92"
  },
  {
    "slug": "santam-drone-claims-notification",
    "insurer": "Santam",
    "title": "Drone Claims Notification Sheet"
  },
  {
    "slug": "santam-motor-accident-claim",
    "insurer": "Santam",
    "title": "Motor Vehicle Own Damage Claim Form",
    "afTitle": "Motorvoertuig Eie Skade Eisvorms"
  },
  {
    "slug": "saws-capital-alliance-funeral-claim",
    "insurer": "Capital Alliance (Liberty)",
    "title": "Funeral Claim Form",
    "description": "Compulsory Benefit"
  },
  {
    "slug": "sintelum-property-claim",
    "insurer": "Sintelum",
    "title": "Property Loss / Damage Claim Form"
  }
];

export const CLAIM_FORM_SCHEMAS: Record<string, ClaimFormSchema> = {
  "aig-corporate-travel-claim": aigCorporateTravelClaim as unknown as ClaimFormSchema,
  "bryte-motor-claim": bryteMotorClaim as unknown as ClaimFormSchema,
  "bryte-non-motor-claim": bryteNonMotorClaim as unknown as ClaimFormSchema,
  "charter-risk-motor-glass-claim": charterRiskMotorGlassClaim as unknown as ClaimFormSchema,
  "charter-risk-motor-vehicle-claim": charterRiskMotorVehicleClaim as unknown as ClaimFormSchema,
  "charter-risk-property-loss-damage-claim": charterRiskPropertyLossDamageClaim as unknown as ClaimFormSchema,
  "glass-claim": glassClaim as unknown as ClaimFormSchema,
  "guardrisk-property-claim": guardriskPropertyClaim as unknown as ClaimFormSchema,
  "horizon-claim": horizonClaim as unknown as ClaimFormSchema,
  "old-mutual-motor-accident-claim": oldMutualMotorAccidentClaim as unknown as ClaimFormSchema,
  "old-mutual-motor-theft-claim": oldMutualMotorTheftClaim as unknown as ClaimFormSchema,
  "old-mutual-property-loss-damage-claim": oldMutualPropertyLossDamageClaim as unknown as ClaimFormSchema,
  "old-mutual-public-liability-accident-report": oldMutualPublicLiabilityAccidentReport as unknown as ClaimFormSchema,
  "santam-drone-claims-notification": santamDroneClaimsNotification as unknown as ClaimFormSchema,
  "santam-motor-accident-claim": santamMotorAccidentClaim as unknown as ClaimFormSchema,
  "saws-capital-alliance-funeral-claim": sawsCapitalAllianceFuneralClaim as unknown as ClaimFormSchema,
  "sintelum-property-claim": sintelumPropertyClaim as unknown as ClaimFormSchema,
};
