// Short stepper labels for the claim form wizard, keyed by the section's full title.
// The JSON schemas are regenerated by scripts/convert-claim-forms.mjs, so the short labels
// live here rather than in the JSON. The full title still heads each section's card.
const SHORT_LABELS: Record<string, string> = {
  // Policy / claim header
  "Notes & Type of Claim": "Type",
  "Type of Loss & Reference": "Loss",
  "Policy & Insured Details": "Policy",
  "Claim & Policy": "Policy",
  "Policy & Broker Details": "Policy",
  "Policy & Claim Number": "Policy",
  Insurer: "Insurer",
  "Claims Notification": "Notification",
  "Checklist and Supporting Documents": "Checklist",
  "Section A: Policy Details": "Policy",

  // People
  Insured: "Insured",
  "The Insured": "Insured",
  "Section 1 – Insured Person": "Insured",
  "Insured & Contact Details": "Insured",
  Driver: "Driver",
  "The Driver at the Time of the Accident": "Driver",
  Passengers: "Passengers",
  "Passengers (Insured Vehicle)": "Passengers",
  Owner: "Owner",
  "Finance Company": "Finance",
  "Section B: Main Member's Details": "Member",
  "Section C: Deceased's Details": "Deceased",
  "Section E: Beneficiary's Details": "Beneficiary",
  Relationship: "Relationship",

  // Third parties and witnesses
  "Other Party": "Third party",
  "Other Party — Other Vehicles": "Third party",
  "If Loss / Damage Was Caused By Another Party": "Third party",
  "Other Party — Personal Injuries": "Injuries",
  "Personal Injuries": "Injuries",
  "Personal Injuries (Other Than in Insured's Vehicle)": "Injuries",
  Witnesses: "Witnesses",
  "Independent Witnesses": "Witnesses",

  // Vehicle and incident
  Vehicle: "Vehicle",
  "The Vehicle": "Vehicle",
  Damage: "Damage",
  Accident: "Accident",
  "The Accident": "Accident",
  "Accident Details": "Accident",
  "Description of Accident": "Accident",
  Incident: "Incident",
  Theft: "Theft",
  "Theft (vehicle theft claims only)": "Theft",
  "Licence Inspected": "Licence",
  "Property Other Than Vehicles": "Property",
  "Property Damage": "Property",

  // Loss / property
  Occurrence: "Occurrence",
  "Loss / Damage Occurrence": "Occurrence",
  "Loss / Damage Address": "Address",
  "Cause of Loss / Damage": "Cause",
  "Previous Loss / Damage": "History",
  Premises: "Premises",
  "Details of Broken Glass": "Glass",
  "Details of Loss": "Loss",
  "Details of a Claim": "Claim",
  Claim: "Claim",
  "Cargo Carried": "Cargo",
  "Police Details": "Police",
  Police: "Police",
  "Other Interest": "Interest",
  "Other Insurance": "Insurance",
  "Other Insurances": "Insurance",
  Other: "Other",
  Value: "Value",
  "Details of Property Lost, Stolen or Damaged": "Items",
  "List of Property Lost, Stolen or Damaged": "Items",
  "Statement of Property Lost, Stolen or Damaged": "Items",
  "Statement — Supporting Documents": "Documents",

  // Travel (AIG)
  "Section 2 – Death / Personal Accident": "Accident",
  "Section 3 – Medical Claims": "Medical",
  "Section 4 – Baggage, Cash and Travel Documents": "Baggage",
  "Missing / Damaged Articles Schedule": "Articles",
  "Section 5 – Cancellation, Curtailment or Alteration": "Cancellation",
  "Section 6 – Travel Delay": "Delay",
  "Section 7 – Personal Liability": "Liability",

  // Payment and sign-off
  "Payment Method": "Payment",
  "Authority for Payment": "Payment",
  "Claim Payment Details": "Payment",
  "Section D: Payment Details (Compulsory)": "Payment",
  Declaration: "Declaration",
  "Declaration And Statement": "Declaration",
  "Information Sharing / Declaration": "Declaration",
  "Section 8 – Electronic Funds Transfer, Declaration and Authority": "Declaration",
  "Section F: Employer Declaration": "Employer",
  "Section G: FICA Requirements": "FICA",
  "Damage to Property POPI Act — Consent": "Consent",
};

/** One- or two-word label for a claim form section, for the step progress bar. */
export function shortStepLabel(title: string): string {
  const known = SHORT_LABELS[title];
  if (known) return known;
  // Unmapped (e.g. a newly converted form): drop a "Section X –" / "The" prefix and keep the first word.
  const stripped = title.replace(/^Section\s+\w+\s*[:–—-]\s*/i, "").replace(/^The\s+/i, "");
  return stripped.split(/[\s/&,—–(]+/).find(Boolean) ?? title;
}
