"use client";

import PageBreadcrumb from "@/components/common/PageBreadCrumb";
import { Table, TableBody, TableCell, TableHeader, TableRow } from "@/components/ui/table";
import { useAuth } from "@/context/AuthContext";
import { findClient, findUser, formatDate, formatDateTime, reportScopeLabel } from "@/lib/mock/helpers";
import { useData } from "@/lib/mock/store";

export default function ReportHistoryPage() {
  const { currentUser } = useAuth();
  const { state } = useData();
  const role = currentUser?.role ?? "broker";

  const reports = state.reports.filter((r) => {
    if (role === "administrator" || role === "manager") return true;
    if (role === "broker") return state.clients.find((c) => c.id === r.clientId)?.brokerId === currentUser?.id;
    return r.clientId === currentUser?.clientId;
  });

  return (
    <div>
      <PageBreadcrumb pageTitle="Report History" />
      <div className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-card dark:border-gray-800 dark:bg-gray-900">
        <Table>
          <TableHeader className="border-b border-gray-200 bg-gray-50/70 dark:border-gray-800 dark:bg-white/2">
            <TableRow>
              <TableCell isHeader className="px-5 py-2.5 text-start text-[11px] font-semibold tracking-wider text-gray-500 uppercase dark:text-gray-400">Type</TableCell>
              <TableCell isHeader className="px-4 py-2.5 text-start text-[11px] font-semibold tracking-wider text-gray-500 uppercase dark:text-gray-400">Client</TableCell>
              <TableCell isHeader className="px-4 py-2.5 text-start text-[11px] font-semibold tracking-wider text-gray-500 uppercase dark:text-gray-400">Scope</TableCell>
              <TableCell isHeader className="px-4 py-2.5 text-start text-[11px] font-semibold tracking-wider text-gray-500 uppercase dark:text-gray-400">Period</TableCell>
              <TableCell isHeader className="px-4 py-2.5 text-start text-[11px] font-semibold tracking-wider text-gray-500 uppercase dark:text-gray-400">Generated By</TableCell>
              <TableCell isHeader className="px-4 py-2.5 text-start text-[11px] font-semibold tracking-wider text-gray-500 uppercase dark:text-gray-400">Generated</TableCell>
            </TableRow>
          </TableHeader>
          <TableBody className="divide-y divide-gray-100 dark:divide-gray-800">
            {reports.length === 0 && (
              <TableRow>
                <TableCell className="px-5 py-6 text-theme-sm text-gray-400">No reports generated yet.</TableCell>
              </TableRow>
            )}
            {reports.map((r) => (
              <TableRow key={r.id}>
                <TableCell className="px-5 py-3 text-theme-sm text-gray-700 sm:px-6 dark:text-gray-300">
                  {r.type === "claims_history" ? "Claims History" : "Performance"}
                </TableCell>
                <TableCell className="px-4 py-3 text-theme-sm text-gray-500 dark:text-gray-400">{findClient(state, r.clientId)?.name}</TableCell>
                <TableCell className="px-4 py-3 text-theme-sm text-gray-500 dark:text-gray-400">
                  {reportScopeLabel(r.scope, state.policies)}
                </TableCell>
                <TableCell className="px-4 py-3 text-theme-xs text-gray-400">
                  {formatDate(r.periodStart)} — {formatDate(r.periodEnd)}
                </TableCell>
                <TableCell className="px-4 py-3 text-theme-sm text-gray-500 dark:text-gray-400">{findUser(state, r.generatedById)?.name}</TableCell>
                <TableCell className="px-4 py-3 text-theme-xs text-gray-400">{formatDateTime(r.generatedAt)}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}
